spring:
    mvc:
        log-resolved-exception: false
    jackson:
        time-zone: Europe/Berlin

springdoc:
    writer-with-order-by-keys: true

server:
    error:
        whitelabel:
            enabled: false

management:
    info:
        env:
            # Enable Exposing of Information over /actuator/info
            enabled: true
    endpoints:
        access:
            max-permitted: read-only
            default: read-only
        web:
            exposure:
                include: health,info,metrics,prometheus,sbom
    endpoint:
        info:
            access: read-only
        prometheus:
            access: read-only
        health:
            access: read-only
            probes:
                access: read-only
        metrics:
            access: read-only
        sbom:
            access: read-only
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true
    tracing:
        propagation:
            type: w3c

logging:
    structured:
        format:
            console: logstash